### ISSUE TITLE
Error receiving broadcast Intent { act=com.google.android.play.core.splitinstall.receiver.SplitInstallUpdateIntentService

### ISSUE THREAD

**Issue by beyondckw** [googlesamples/android-dynamic-features#48]
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.play.core.splitinstall.receiver.SplitInstallUpdateIntentService flg=0x40000010 pkg=com.xxx.xxx (has extras) } in com.google.android.play.core.a.c@f8b72c9
       at android.app.LoadedApk$ReceiverDispatcher$Args.run + 932(LoadedApk.java:932)
       at android.os.Handler.handleCallback + 815(Handler.java:815)
       at android.os.Handler.dispatchMessage + 104(Handler.java:104)
       at android.os.Looper.loop + 207(Looper.java:207)
       at android.app.ActivityThread.main + 5788(ActivityThread.java:5788)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 789(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main + 679(ZygoteInit.java:679)
Caused by java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry + 787(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next + 814(HashMap.java:814)
       at com.google.android.play.core.listener.a.a$1385ff(a.java)
       at com.google.android.play.core.splitinstall.k.a(k.java:2000)
       at com.google.android.play.core.splitinstall.k.a(k.java:2000)
       at com.google.android.play.core.splitinstall.SplitInstallSessionState.status(SplitInstallSessionState.java:2000)
       at com.google.android.play.core.splitinstall.k.a(k.java:2000)
       at com.google.android.play.core.splitinstall.k.a(k.java:2000)
       at com.google.android.play.core.listener.b.onReceive(b.java)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run + 922(LoadedApk.java:922)
       at android.os.Handler.handleCallback + 815(Handler.java:815)
       at android.os.Handler.dispatchMessage + 104(Handler.java:104)
       at android.os.Looper.loop + 207(Looper.java:207)
       at android.app.ActivityThread.main + 5788(ActivityThread.java:5788)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 789(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main + 679(ZygoteInit.java:679)

**Comment by vyshas** [comment]
have this same issue

**Comment by ammar-ali** [comment]
Any update on this issue

**Comment by ammar-ali** [comment]
Any update on this issue

**Comment by KennethCJ** [comment]
i fix this issue by doing two thing below,but i dont know which one actually took effect
1,add 'synchronized' when calling function 'splitInstallManager.registerListener' and 'splitInstallManager.unregisterListener' 
2, call function 'splitInstallManager.registerListener'  when OnFailureListener.onFailure  callback

Hope can help.
