### ISSUE TITLE
Tests in dynamic feature module fail when run through gradle command line

### ISSUE THREAD

**Issue by RafaO** [googlesamples/android-dynamic-features#54]
I wrote some tests for a Dynamic Feature Module inside `DynamicFeature/src/test/java/my/package/MyTest.kt`. These tests rely on a class that is hosted in the main `app` module. If I run the tests using the Android Studio configuration they run without problems, but on the other hand if I use `./gradlew test` they fail saying that the class on the main module can't be found: 
```
    java.lang.NoClassDefFoundError
        Caused by: java.lang.ClassNotFoundException
```

In order to include the tests inside my CI, I would need either to know how to get the command line order that Android Studio is using, or figure out why when running the gradle task, it is not able to find the main module app.

Any help appreciated.
Thanks in advance!

**Comment by linean** [comment]
I have the same problem and I also haven't found the solution.

**Comment by pgreze** [comment]
I'm facing the same issue as well. In my case code is in a common module shared by app and feature modules.

Full message is:
```
com.kouzoh.mercari.... > initializationError FAILED
    java.lang.NoClassDefFoundError
        Caused by: java.lang.ClassNotFoundException
```

Junit report:

```
java.lang.NoClassDefFoundError: Lcom/kouzoh/mercari/...;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.junit.runners.model.TestClass.getSortedDeclaredFields(TestClass.java:77)
	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:70)
	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
...
Caused by: java.lang.ClassNotFoundException: com.kouzoh.mercari...
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by arohim** [comment]
I have the same issue, no solution yet.

**Comment by svlima6669** [comment]
Interesting,making a project that Google wont accept. I had not expected that anyway and i thougth that is possible to make something without going to Google.

**Comment by TomMarshBBC** [comment]
Upgrading to com.android.tools.build:gradle:3.5.0 causes instrumentation tests in my dynamic feature modules to crash. Reverting back to 3.4.2 is the only solution I can find at the moment. Is this a known issue?
